package Callcenter;

public enum Provincia {
	BUENOS_AIRES, CABA, ENTRE_RIOS, CORRIENTES, SANTA_FE, MISIONES, 
	FORMOSA, CHACO, SALTA, TUCUMAN, CATAMARCA, SANTIAGO_DEL_ESTERO,
	SAN_JUAN,LA_RIOJA,CORDOBA, MENDOZO, NEUQUEN,JUJUY, LA_PAMPA, SAN_LUIS, SANTA_CRUZ, 
	RIO_NEGRO , CHUBUT, TIERRA_DEL_FUEGO 
}
